CREATE TABLE PRODUCT (
    PRODUCT_ID SERIAL PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_TYPE VARCHAR(50),
    PRICE NUMERIC(10,2),
    STOCK INTEGER,
    DESCRIPTION VARCHAR(500),

    ATTRIBUTE_CATEGORIES VARCHAR(200),
    ATTRIBUTE1 VARCHAR(200),
    ATTRIBUTE2 VARCHAR(200),
    ATTRIBUTE3 VARCHAR(200),
    ATTRIBUTE4 VARCHAR(200),
    ATTRIBUTE5 VARCHAR(200),
    ATTRIBUTE6 VARCHAR(200),
    ATTRIBUTE7 VARCHAR(200),
    ATTRIBUTE8 VARCHAR(200),
    ATTRIBUTE9 VARCHAR(200),
    ATTRIBUTE10 VARCHAR(200),
    ATTRIBUTE11 VARCHAR(200),
    ATTRIBUTE12 VARCHAR(200),
    ATTRIBUTE13 VARCHAR(200),
    ATTRIBUTE14 VARCHAR(200),
    ATTRIBUTE15 VARCHAR(200),

    CREATED_BY INTEGER,
    CREATION_DATE DATE,
    LAST_UPDATED_BY INTEGER,
    LAST_UPDATED_DATE DATE,
    LAST_UPDATED_LOGIN INTEGER
);

CREATE TABLE MEMBER (
    MEMBER_ID SERIAL PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(100),
    PHONE VARCHAR(15),
    EMAIL_ID VARCHAR(100),
    GENDER VARCHAR(10),

    ATTRIBUTE_CATEGORIES VARCHAR(200),
    ATTRIBUTE1 VARCHAR(200),
    ATTRIBUTE2 VARCHAR(200),
    ATTRIBUTE3 VARCHAR(200),
    ATTRIBUTE4 VARCHAR(200),
    ATTRIBUTE5 VARCHAR(200),
    ATTRIBUTE6 VARCHAR(200),
    ATTRIBUTE7 VARCHAR(200),
    ATTRIBUTE8 VARCHAR(200),
    ATTRIBUTE9 VARCHAR(200),
    ATTRIBUTE10 VARCHAR(200),
    ATTRIBUTE11 VARCHAR(200),
    ATTRIBUTE12 VARCHAR(200),
    ATTRIBUTE13 VARCHAR(200),
    ATTRIBUTE14 VARCHAR(200),
    ATTRIBUTE15 VARCHAR(200),

    CREATED_BY INTEGER,
    CREATION_DATE DATE,
    LAST_UPDATED_BY INTEGER,
    LAST_UPDATED_DATE DATE,
    LAST_UPDATED_LOGIN INTEGER
);

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID SERIAL PRIMARY KEY,
    PRODUCT_ID INTEGER,
    MEMBER_ID INTEGER,
    QUANTITY INTEGER,
    TRANSACTION_DATE DATE,
    APPROVED_STATUS VARCHAR(20),

    ATTRIBUTE_CATEGORIES VARCHAR(200),
    ATTRIBUTE1 VARCHAR(200),
    ATTRIBUTE2 VARCHAR(200),
    ATTRIBUTE3 VARCHAR(200),
    ATTRIBUTE4 VARCHAR(200),
    ATTRIBUTE5 VARCHAR(200),
    ATTRIBUTE6 VARCHAR(200),
    ATTRIBUTE7 VARCHAR(200),
    ATTRIBUTE8 VARCHAR(200),
    ATTRIBUTE9 VARCHAR(200),
    ATTRIBUTE10 VARCHAR(200),
    ATTRIBUTE11 VARCHAR(200),
    ATTRIBUTE12 VARCHAR(200),
    ATTRIBUTE13 VARCHAR(200),
    ATTRIBUTE14 VARCHAR(200),
    ATTRIBUTE15 VARCHAR(200),

    CREATED_BY INTEGER,
    CREATION_DATE DATE,
    LAST_UPDATED_BY INTEGER,
    LAST_UPDATED_DATE DATE,
    LAST_UPDATED_LOGIN INTEGER,

    CONSTRAINT FK_TRANS_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_TRANS_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

CREATE TABLE CART (
    CART_ID SERIAL PRIMARY KEY,
    PRODUCT_ID INTEGER,
    MEMBER_ID INTEGER,
    QUANTITY INTEGER,

    ATTRIBUTE_CATEGORIES VARCHAR(200),
    ATTRIBUTE1 VARCHAR(200),
    ATTRIBUTE2 VARCHAR(200),
    ATTRIBUTE3 VARCHAR(200),
    ATTRIBUTE4 VARCHAR(200),
    ATTRIBUTE5 VARCHAR(200),
    ATTRIBUTE6 VARCHAR(200),
    ATTRIBUTE7 VARCHAR(200),
    ATTRIBUTE8 VARCHAR(200),
    ATTRIBUTE9 VARCHAR(200),
    ATTRIBUTE10 VARCHAR(200),
    ATTRIBUTE11 VARCHAR(200),
    ATTRIBUTE12 VARCHAR(200),
    ATTRIBUTE13 VARCHAR(200),
    ATTRIBUTE14 VARCHAR(200),
    ATTRIBUTE15 VARCHAR(200),

    CREATED_BY INTEGER,
    CREATION_DATE DATE,
    LAST_UPDATED_BY INTEGER,
    LAST_UPDATED_DATE DATE,
    LAST_UPDATED_LOGIN INTEGER,

    CONSTRAINT FK_CART_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_CART_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

CREATE TABLE RATING (
    RATING_ID SERIAL PRIMARY KEY,
    PRODUCT_ID INTEGER,
    MEMBER_ID INTEGER,
    VALUE INTEGER CHECK (VALUE BETWEEN 1 AND 5),

    ATTRIBUTE_CATEGORIES VARCHAR(200),
    ATTRIBUTE1 VARCHAR(200),
    ATTRIBUTE2 VARCHAR(200),
    ATTRIBUTE3 VARCHAR(200),
    ATTRIBUTE4 VARCHAR(200),
    ATTRIBUTE5 VARCHAR(200),
    ATTRIBUTE6 VARCHAR(200),
    ATTRIBUTE7 VARCHAR(200),
    ATTRIBUTE8 VARCHAR(200),
    ATTRIBUTE9 VARCHAR(200),
    ATTRIBUTE10 VARCHAR(200),
    ATTRIBUTE11 VARCHAR(200),
    ATTRIBUTE12 VARCHAR(200),
    ATTRIBUTE13 VARCHAR(200),
    ATTRIBUTE14 VARCHAR(200),
    ATTRIBUTE15 VARCHAR(200),

    CREATED_BY INTEGER,
    CREATION_DATE DATE,
    LAST_UPDATED_BY INTEGER,
    LAST_UPDATED_DATE DATE,
    LAST_UPDATED_LOGIN INTEGER,

    CONSTRAINT FK_RATING_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_RATING_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

